[package]
name = "pixelflut"
version = "0.1.0"
authors = ["Stefan Zabka <stefan.zabka@hu-berlin.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
rand = "0.7.2"
